--- # installing the httpd package on my local machine 
- hosts: test
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install httpd rpm in centos
      action: yum name=httpd state=installed
